version: "3.3"

volumes:
  mariadb:
    driver: local
    driver_opts:
      device: /home/amylle/data/mariadb
      o: bind
      type: none
  wordpress:
    driver: local
    driver_opts:
      device: /home/amylle/data/wordpress
      o: bind
      type: none

networks:
  inception_network:
    name: inception_network
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    image: mariadb:1.0
    networks:
      - inception_network
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
    env_file: 
      - .env
    restart: unless-stopped
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: nginx:1.0
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    ports:
      - "443:443"
    networks:
      - inception_network
    env_file:
      - .env
    restart: unless-stopped
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    image: wordpress:1.0
    depends_on: 
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception_network
    env_file:
      - .env
    restart: unless-stopped
