name: inception

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    image: mariadb:1.0
    restart: always
    networks:
      - inception_network
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
